// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/signer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignerService_StreamSignRequests_FullMethodName = "/signer.SignerService/StreamSignRequests"
	SignerService_ReportSignResult_FullMethodName   = "/signer.SignerService/ReportSignResult"
)

// SignerServiceClient is the client API for SignerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignerServiceClient interface {
	StreamSignRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignRequest], error)
	ReportSignResult(ctx context.Context, in *SignResult, opts ...grpc.CallOption) (*Empty, error)
}

type signerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerServiceClient(cc grpc.ClientConnInterface) SignerServiceClient {
	return &signerServiceClient{cc}
}

func (c *signerServiceClient) StreamSignRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignerService_ServiceDesc.Streams[0], SignerService_StreamSignRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, SignRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignerService_StreamSignRequestsClient = grpc.ServerStreamingClient[SignRequest]

func (c *signerServiceClient) ReportSignResult(ctx context.Context, in *SignResult, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SignerService_ReportSignResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServiceServer is the server API for SignerService service.
// All implementations must embed UnimplementedSignerServiceServer
// for forward compatibility.
type SignerServiceServer interface {
	StreamSignRequests(*Empty, grpc.ServerStreamingServer[SignRequest]) error
	ReportSignResult(context.Context, *SignResult) (*Empty, error)
	mustEmbedUnimplementedSignerServiceServer()
}

// UnimplementedSignerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignerServiceServer struct{}

func (UnimplementedSignerServiceServer) StreamSignRequests(*Empty, grpc.ServerStreamingServer[SignRequest]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSignRequests not implemented")
}
func (UnimplementedSignerServiceServer) ReportSignResult(context.Context, *SignResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSignResult not implemented")
}
func (UnimplementedSignerServiceServer) mustEmbedUnimplementedSignerServiceServer() {}
func (UnimplementedSignerServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServiceServer will
// result in compilation errors.
type UnsafeSignerServiceServer interface {
	mustEmbedUnimplementedSignerServiceServer()
}

func RegisterSignerServiceServer(s grpc.ServiceRegistrar, srv SignerServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignerService_ServiceDesc, srv)
}

func _SignerService_StreamSignRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignerServiceServer).StreamSignRequests(m, &grpc.GenericServerStream[Empty, SignRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignerService_StreamSignRequestsServer = grpc.ServerStreamingServer[SignRequest]

func _SignerService_ReportSignResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).ReportSignResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_ReportSignResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).ReportSignResult(ctx, req.(*SignResult))
	}
	return interceptor(ctx, in, info, handler)
}

// SignerService_ServiceDesc is the grpc.ServiceDesc for SignerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signer.SignerService",
	HandlerType: (*SignerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSignResult",
			Handler:    _SignerService_ReportSignResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignRequests",
			Handler:       _SignerService_StreamSignRequests_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/signer.proto",
}
